---
Name: build_data_object
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'build/dataobject//$Action/$ID/$OtherID': 'Sunnysideup\BuildDataObject\Control\Models\DataObjectBuildController'
    'build/page//$Action/$ID/$OtherID': 'Sunnysideup\BuildDataObject\Control\Models\PageBuildController'
