---
Name: build_data_object
After: '#rootroutes'
---
Director:
  rules:
    'build/dataobject//$Action/$ID/$OtherID': 'Sunnysideup\BuildDataObject\DataObjectBuildController'
    'build/page//$Action/$ID/$OtherID': 'Sunnysideup\BuildDataObject\PageBuildController'
